@MatchMaking.Service_HostAddress = http://localhost:5058
@MatchControllerPefix = api/match

### Search Request
POST {{MatchMaking.Service_HostAddress}}/{{MatchControllerPefix}}/request
Content-Type: application/json
Accept: application/json
UserId: user_1

### Get Matches
GET {{MatchMaking.Service_HostAddress}}/{{MatchControllerPefix}}/matches
Accept: application/json
UserId: user_5